### ISSUE TITLE
Getting TestIds configuration error even when TestIds not configured in the test interface

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/test_ids#9]
Hi,

I previously had setup some TestId configs in my test interface.  Then I wrapped said configuration in a conditional and when that condition is not true, I get this error when executing the flow generation:

~~~shell
COMPLETE CALL STACK
-------------------
You have to create the configuration first before you can access it
/users/user/origen/github/test_ids/lib/test_ids.rb:52:in `configuration'
/users/user/origen/github/test_ids/lib/test_ids.rb:47:in `current_configuration'
/users/user/origen/github/test_ids/lib/test_ids/origen_testers/flow.rb:14:in `test'
/users/user/origen/ruby/2.3.0/bundler/gems/origen_testers-e3e8ac86e9c9/lib/origen_testers/interface.rb:46:in `test'
~~~

Here is a debugger snapshot that shows the configuration id is nil, yet it seems to think nil is a valid configuration.

~~~ruby
From: /users/user/origen/github/test_ids/lib/test_ids.rb @ line 52 TestIds.configuration:

    50: def configuration(id)
    51:   binding.pry
 => 52:   return @configuration[id] if @configuration && @configuration[id]
    53:   fail('You have to create the configuration first before you can access it')
    54: end

[1] pry(TestIds)> id
=> nil
[2] pry(TestIds)> @configuration
=> nil
~~~

I can't figure out why TestIds is even running if I am not configuring it in the interface.  I even got rid of the test_ids directory in the imports path with no luck.

thx

**Comment by info-rchitect** [comment]
sorry found a place i was accessing the TestIds.allocate method

**Comment by info-rchitect** [comment]
actually even removing that call to TestIds.allocate, I still get the same error.

**Comment by priyavadan** [comment]
I don't think I understand. Maybe you still have a reference to TestIds in your app somewhere?

**Comment by ginty** [comment]
It's complaining because you are calling TestIds.current_configuration here - https://github.com/Origen-SDK/test_ids/blob/master/lib/test_ids/origen_testers/flow.rb#L14

That should be gated by TestIds.configured? as in the code on the preceding lines.

**Comment by info-rchitect** [comment]
[Fixed](https://github.com/Origen-SDK/test_ids/pull/10)
